### PR TITLE
Igk igl coords

### PR DESCRIPTION
**Pull request by William-Gibson-ig**
Pushing renamed IGL/IGL coord files for Human to master

### CODE REVIEW

**Comment by William-Gibson-ig** [comment]
Sorted the IGK and IGL coords to be ascending

**Comment by oscarlr** [comment]
Can you use this code to sort: sort -k1,1 -k2,2n <bed> > <sorted bed>

**Comment by William-Gibson-ig** [comment]
Ok did the sort with -k1,1 -k2,2n and have the files renamed to sorted. If you wanted to check those before merging and renaming (or I can rename after you check them).

**Comment by oscarlr** [comment]
The sorted files look good. Can you rename them to the original file names?

**Review by oscarlr — APPROVED** [review]
Looks good.

**Pull request merged**
